#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Dec 14 23:24:28 2018

@author: rrui
"""
def f(num):
    if num % 2 == 0:
        return num // 2
    else:
        return 3*num + 1
    
    