#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Dec 23 22:22:18 2018

@author: rrui
"""

def gradingStudents(grades):
    for i in range(len(grades)):
        if(grades[i]>37):
            if((grades[i]%5)!=0):
                if(grades[i]%5>2):
                    grades[i]+=5-(grades[i]%5)
    return (grades)
    
grades = [73, 67, 38, 33]
print(gradingStudents(grades))