#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Dec 24 10:39:13 2018

@author: rrui
"""

def kangaroo(x1, v1, x2, v2):
    while v2 < v1:
        if (x2 - x1) % (v1 - v2) != 0:
            return "NO"
        else:
            return "YES"
    return "NO"
    
x1, v1, x2, v2 = 0, 2, 5, 3
print(kangaroo(x1, v1, x2, v2))