#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Dec 22 22:16:42 2018

@author: rrui
"""



def miniMaxSum(arr):
    print(int(sum(arr)-max(arr)),int(sum(arr)-min(arr)))

arr = [1,2,3,4,5]
print(miniMaxSum(arr))
        