#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Dec 14 22:39:53 2018

@author: rrui
"""

def pig_latin(word):
    first_letter = word[0]
    rest_letter = word[1:]
    
    if (first_letter == "a" or first_letter == "e" or first_letter == "i"
        or first_letter == "o" or first_letter == "u"):
        return word + "way"
    else: 
        return rest_letter + first_letter + "ay"
    