#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Dec 21 20:06:18 2018

@author: rrui
"""

def sumofrange(ar):
    n = 0
    for i in ar:
        n = n + i
    return n




           
            