#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Dec 14 22:54:42 2018

@author: rrui
"""

def smaller_root(a,b,c):
    discriminant = b**2 - 4*a*c
    if discriminant < 0 or a == 0:
        print("Error: No real solution")
    else: 
        if a > 0:
            smaller = -discriminant ** 0.5
        else: 
            smaller = discriminant ** 0.5
        return (-b + smaller) / (2 * a)