#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the sockMerchant function below.
def sockMerchant(n, ar):
    cct = {i:ar.count(i) for i in ar}
    ctt = list(cct.values())
    s = 0
    for x in ctt:
        if x % 2 == 0:
            s += x / 2
        else:
            s += (x - 1) / 2
    return int(s) 

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    ar = list(map(int, input().rstrip().split()))

    result = sockMerchant(n, ar)

    fptr.write(str(result) + '\n')

    fptr.close()
