#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Dec 22 23:26:53 2018

@author: rrui
"""


def timeConversion(s):
        if s[:2] == "12":
            if s[-2:] == "PM":
                return s[:-2]
            else:
                return str("00") + s[2:8]
        elif s[-2:] == "PM":
            return str(int(s[:2]) + 12 ) + s[2:8]
        else:
            return s[:-2]


s = "12:40:22AM"
print(timeConversion(s))

print(s[:2])
